version: '2'
services:
  nginx:
    build:
      context: ./containers/http/nginx
      dockerfile: Dockerfile.dev
    volumes:
      - ./containers/http/nginx/nginx.dev.conf:/etc/nginx/nginx.conf
    ports:
      - 0.0.0.0:8080:8080
  frontend:
    build:
      context: ./containers/frontend/my-app
      dockerfile: Dockerfile.dev
    volumes:
      - ./containers/frontend/my-app/contents:/opt/app
      - /opt/app/node_modules
    ports:
      - 127.0.0.1:3000:3000
    stdin_open: true
  redis:
    build:
      context: ./containers/nosql/redis
      dockerfile: Dockerfile.dev
    ports:
      - 127.0.0.1:6379:6379
  postgres:
    image: postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - "./containers/sql/postgres/postgres-data:/var/lib/postgresql/data"
    ports:
      - "127.0.0.1:5432:5432"
